development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: pinterest-clone_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: pinterest-clone_test
  pool: 5
